name: calculator testing and create release
on:
    push:
        branches: [main]
        tags:
          - '*.*.*'
jobs:
    build:
        name: Build my virtual OS

        runs-on: Ubuntu-latest

        steps:

        - name: calculator testing
          uses: actions/checkout@v4
          with:
             repository: smickey/pytest_for_calculator

        - name: Show files
          run: |
             ls
             cp test_calculator.py /home/runner/work/
             pwd

        - name: checkout my codes
          uses: actions/checkout@v4
          

        - name: Show files
          run: |
             ls
             pwd
             mv /home/runner/work/test_calculator.py .

        - name: Set up Python 3.8
          uses: actions/setup-python@v4
          with:
            python-version: "3.8"
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pytest

        - name: Test with Pytest
          run: |
            pytest test_calculator.py
            
        - name: Extract release notes
          id: extract-release-notes
          uses: ffurrer2/extract-release-notes@v2
        - name: Create release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: gh release create --notes '${{ steps.extract-release-notes.outputs.release_notes }}' --title ${{ github.ref_name }} ${{ github.ref_name }}
