name: calculator testing
on:
    push:
        branches: [main]
jobs:
    build:

        name: Build my virtual OS

        runs-on: Ubuntu-latest

        steps:

        - name: checkout my codes
          uses: actions/checkout@v4
          

        - name: Show files
          run: |
             ls
             pwd
             cp calculator.py /home/runner/work/

        - name: calculator testing
          uses: actions/checkout@v4
          with:
             repository: smickey/pytest_for_calculator
             
             
        - name: Show files
          run: |
             ls
             mv /home/runner/work/calculator.py .
             pwd

        - name: Set up Python 3.8
          uses: actions/setup-python@v4
          with:
            python-version: "3.8"
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pytest

        - name: Test with Pytest
          run: |
            pytest test_calculator.py

name: Create Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v2
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create --notes '${{ steps.extract-release-notes.outputs.release_notes }}' --title ${{ github.ref_name }} ${{ github.ref_name }}
