name: calculator testing
on:
    push:
        branches: [main]
jobs:
    build:

        name: Build my virtual OS

        runs-on: Ubuntu-latest

        steps:

        - name: checkout my codes
          uses: actions/checkout@v2
          

        - name: Show files
          run: |
             ls
             pwd
             cp calculator.py /home/runner/work/

        - name: calculator testing
          uses: actions/checkout@v2
          with:
             repository: smickey/pytest_for_calculator
             
             
        - name: Show files
          run: |
             ls
             mv /home/runner/work/calculator.py .
             pwd

        - name: Set up Python 3.8
          uses: actions/setup-python@v3
          with:
            python-version: "3.8"
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pytest

        - name: Test with Pytest
          run: |
            pytest test_calculator.py
