name: calculator testing
on:
    push:
        branches: [main]
jobs:
    build:

        name: Build my virtual OS

        runs-on: Ubuntu-latest

        steps:

        - name: checkout my codes
          uses: actions/checkout@v2

        - name: Show files
          run: |
             ls

        - name: calculator testing
          uses: actions/checkout@v2
          with:
             repository: smickey/pytest_for_calculator
             #path: <folder of choice>
             
        - name: Show files
          run: |
             ls

        - name: Set up Python 3.8
          uses: actions/setup-python@v3
          with:
            python-version: "3.8"
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pytest

        - name: Test with Pytest
          run: |
            pytest
